-- Add specific EmailType enum values for application status change emails
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'APPLICATION_SHORTLISTED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'APPLICATION_INTERVIEW_REQUESTED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'APPLICATION_ACCEPTED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'APPLICATION_REJECTED';
