// scripts/generate-secrets.js
// Works on Windows (PowerShell, CMD), Mac, and Linux.
// Run from project root: node scripts/generate-secrets.js
//
// Or append directly to backend/.env:
//   node scripts/generate-secrets.js >> backend/.env

const crypto = require("crypto");

const jwtAccess     = crypto.randomBytes(64).toString("base64");
const jwtRefresh    = crypto.randomBytes(64).toString("base64");
const encryptionKey = crypto.randomBytes(32).toString("hex");
const cronSecret    = crypto.randomBytes(32).toString("base64");

// Safety check — they must all be different
if (jwtAccess === jwtRefresh) {
  console.error("ERROR: Generated identical JWT secrets. Re-run the script.");
  process.exit(1);
}

const output = `
# ── Generated by scripts/generate-secrets.js ─────────────────
# Generated: ${new Date().toISOString()}
# Paste these into backend/.env

JWT_ACCESS_SECRET=${jwtAccess}
JWT_REFRESH_SECRET=${jwtRefresh}
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=30d

ENCRYPTION_KEY=${encryptionKey}

CRON_SECRET=${cronSecret}
`.trim();

console.log("\n" + "=".repeat(60));
console.log("  Direct Hire — Generated Secrets");
console.log("=".repeat(60));
console.log("\nCopy the block below into your backend/.env file:\n");
console.log("-".repeat(60));
console.log(output);
console.log("-".repeat(60));
console.log(`
IMPORTANT:
  - JWT_ACCESS_SECRET  (${jwtAccess.length} chars) ✓
  - JWT_REFRESH_SECRET (${jwtRefresh.length} chars) ✓ different from ACCESS
  - ENCRYPTION_KEY     (${encryptionKey.length} hex chars = 32 bytes) ✓
  - CRON_SECRET        generated ✓

Back up ENCRYPTION_KEY before deploying.
Losing it makes all encrypted DB fields unreadable.
`);
