-- Add APPLICATION_RECEIVED to EmailType enum
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'APPLICATION_RECEIVED';

-- Add APPLICATION_SUBMITTED to NotificationType enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPLICATION_SUBMITTED';
