-- Growth/Marketing agent system scaffolding — infrastructure only, no
-- relations to any existing table. Two new tables + one new enum, purely
-- additive.
--
-- Hand-authored rather than generated by `prisma migrate dev`: the shadow
-- database this project's migrate workflow depends on fails to replay
-- cleanly (pre-existing issue, migration `20260404000000_add_otp_verification`
-- errors with P1014/P3006 against a fresh shadow DB — unrelated to this
-- change, not fixed here). SQL below follows the same conventions already
-- established in this migrations folder (see e.g.
-- 20260405000000_add_audit_log/migration.sql for the CREATE TYPE wrapper,
-- and 20260719000000_add_external_job/migration.sql for the CREATE TABLE
-- style). NOT applied — run manually.

-- CreateEnum
DO $$
BEGIN
  CREATE TYPE "GrowthTaskStatus" AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'AWAITING_APPROVAL',
    'APPROVED',
    'REJECTED',
    'COMPLETED',
    'FAILED'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- CreateTable: growth_agent_tasks
CREATE TABLE IF NOT EXISTS "growth_agent_tasks" (
  "id"               TEXT               NOT NULL,

  "agent_name"       TEXT               NOT NULL,
  "task_type"        TEXT               NOT NULL,
  "status"           "GrowthTaskStatus" NOT NULL DEFAULT 'PENDING',

  "input_data"       JSONB,
  "output_data"      JSONB,
  "summary"          TEXT,
  "error_message"    TEXT,

  "approved_by"      TEXT,
  "approved_at"      TIMESTAMP(3),
  "rejected_at"      TIMESTAMP(3),
  "rejection_reason" TEXT,

  "created_at"       TIMESTAMP(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"       TIMESTAMP(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "growth_agent_tasks_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "growth_agent_tasks_agent_name_idx" ON "growth_agent_tasks"("agent_name");
CREATE INDEX IF NOT EXISTS "growth_agent_tasks_status_idx"     ON "growth_agent_tasks"("status");
CREATE INDEX IF NOT EXISTS "growth_agent_tasks_created_at_idx" ON "growth_agent_tasks"("created_at");

-- CreateTable: growth_content_drafts
CREATE TABLE IF NOT EXISTS "growth_content_drafts" (
  "id"                TEXT               NOT NULL,

  "content_type"      TEXT               NOT NULL,
  "title"             TEXT               NOT NULL,
  "slug"              TEXT               NOT NULL,
  "body"              TEXT               NOT NULL,

  "meta_title"        VARCHAR(70),
  "meta_description"  VARCHAR(200),
  "target_keyword"    TEXT,
  "source_task_id"    TEXT,

  "status"            "GrowthTaskStatus" NOT NULL DEFAULT 'PENDING',
  "published_at"      TIMESTAMP(3),

  "created_at"        TIMESTAMP(3)       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"        TIMESTAMP(3)       NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "growth_content_drafts_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "growth_content_drafts_slug_key"         ON "growth_content_drafts"("slug");
CREATE INDEX IF NOT EXISTS        "growth_content_drafts_content_type_idx" ON "growth_content_drafts"("content_type");
CREATE INDEX IF NOT EXISTS        "growth_content_drafts_status_idx"       ON "growth_content_drafts"("status");
